/////////////////////////////////////////INI//////////////////////

var CONST = {
  SPACE: "\u0020",
  NBS: "&nbsp",
  NEWLINE: "\n"
};
var INI = {
  sprite_maxW: 300,
  sprite_maxH: 100
};
INI.COLLISION_SAFE = 264; //UPDATE
INI.TITLE_HEIGHT = 72;
INI.GAME_HEIGHT = 512;
INI.BULLET_SPEED = 12;
INI.HERO_HEALTH = 20;
INI.HERO_REVIVE = 5000;
INI.GAME_OVER = 2000;
INI.BULLET_HEALTH_DECREASE = 3;
INI.APPLE_HEALTH = 5;
INI.PINEAPPLE_HEALTH = 10;
INI.CAKE_HEALTH = 20;
INI.MAX_BULLETS = 7;
INI.TOPMID = 0;

/* CastleHunt MAP*/
var MAP = {
  room0: {
    id: 0,
    name: "the throne room",
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall,
    floor: StoneFloor3,
    ndoor: null,
    edoor: "open",
    sdoor: "open",
    wdoor: null,
    eCon: 1,
    sCon: 46,
    furniture: [
      FURNITURE.rug3,
      FURNITURE.fireplaceL,
      FURNITURE.fireplaceR,
      FURNITURE.tapestry1L,
      FURNITURE.WallLamp_RL,
      FURNITURE.WallLamp_RR,
      FURNITURE.JSW2_TC,
      FURNITURE.LSL3_BL
    ],
    items: [],
    enemy: [ENEMIES.Death1, ENEMIES.Death2, ENEMIES.Death22, ENEMIES.Death11]
  },
  room1: {
    id: 1,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall,
    floor: DungeonFloor2,
    ndoor: "wood1",
    edoor: "open",
    sdoor: "wood1",
    wdoor: "yellow2",
    eCon: 2,
    wCon: 0,
    nCon: 3,
    sCon: 4,
    furniture: [
      FURNITURE.PIC_Hobbit_BL,
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR,
      FURNITURE.wallLamp_RB,
      FURNITURE.Pitfall_BT_W_R
    ],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.time)],
    enemy: [ENEMIES.Rambler]
  },
  room2: {
    id: 2,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: DungeonWall,
    floor: StoneFloor,
    ndoor: null,
    edoor: "orange2",
    sdoor: "open",
    wdoor: "green",
    wCon: 1,
    sCon: 9,
    eCon: 43,
    furniture: [
      FURNITURE.PIC_AA_TC,
      FURNITURE.torch_H_LL,
      FURNITURE.torch_H_LR,
      FURNITURE.GRB_right_L_H,
      FURNITURE.GRB_right_R_H
    ],
    enemy: [ENEMIES.Death11],
    items: [
      $.extend(true, {}, ITEMS.health),
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.bomb)
    ]
  },
  room3: {
    id: 3,
    name: "the Rainbow room",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall2,
    floor: MorgueFloor,
    ndoor: "wood1",
    edoor: "orange2",
    sdoor: "open",
    wdoor: "wood2",
    sCon: 1,
    wCon: 5,
    nCon: 6,
    eCon: 7,
    furniture: [
      FURNITURE.PC_Hero_TR,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.Pitfall3_right_R
    ],
    items: [ITEMS.Pear, $.extend(true, {}, ITEMS.ammo)],
    container: {
      furniture: FURNITURE.chest,
      item: ITEMS.Coin1
    },
    enemy: [ENEMIES.Skeleton, ENEMIES.Skeleton, ENEMIES.Death22]
  },
  room4: {
    id: 4,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall,
    floor: StoneFloor3,
    ndoor: "open",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 1,
    sCon: 8,
    furniture: [
      FURNITURE.lanternPoleL,
      FURNITURE.lanternPoleR,
      FURNITURE.tapestry6L_HR,
      FURNITURE.LTUT_right_H
    ],
    enemy: [ENEMIES.Rambler, ENEMIES.RamblingSnake]
  },
  room5: {
    id: 5,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall3,
    floor: ThachFloor,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "red2",
    eCon: 3,
    wCon: 50,
    furniture: [
      FURNITURE.tapestry7T_H,
      FURNITURE.tree1_TL,
      FURNITURE.tree2_TR,
      FURNITURE.tapestry2B,
      FURNITURE.Phara_left_R,
      FURNITURE.RRR_left_L,
      FURNITURE.wallLamp_RL,
      FURNITURE.wallLamp_RR,
      FURNITURE.Dig_right_R
    ],
    enemy: [ENEMIES.Shooter, ENEMIES.Skeleton7, ENEMIES.SnakeHunter],
    player: PLAYERS.squirrel,
    alertFlag: true,
    alert: "The squirrel looks hungry ...",
    items: [$.extend(true, {}, ITEMS.health2), $.extend(true, {}, ITEMS.ammo)]
  },
  room6: {
    id: 6,
    name: "the Skully's",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall,
    floor: MorgueFloor,
    ndoor: null,
    edoor: "wood2",
    sdoor: "open",
    wdoor: "red2",
    sCon: 3,
    eCon: 27,
    wCon: 32,
    furniture: [
      FURNITURE.PIC_DM_TR,
      FURNITURE.tallClock_TL,
      FURNITURE.HOB2_left_L,
      FURNITURE.rug3,
      FURNITURE.RRR_BT_R,
      FURNITURE.WallLamp_RL,
      FURNITURE.WallLamp_RR,
      FURNITURE.lanternPoleLS,
      FURNITURE.lanternPoleRS
    ],
    items: [$.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.Rambler, ENEMIES.Rambler, ENEMIES.Rambler]
  },
  room7: {
    id: 7,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: CastleWall,
    floor: Pavement2,
    ndoor: null,
    edoor: "wood2",
    sdoor: null,
    wdoor: "open",
    wCon: 3,
    eCon: 13,
    furniture: [
      FURNITURE.PIC_PAC_BC,
      FURNITURE.tallClock_BL,
      FURNITURE.Vixen2_BT_W_R
    ],
    items: [$.extend(true, {}, ITEMS.health2)],
    enemy: [ENEMIES.Rambler]
  },
  room8: {
    id: 8,
    name: "Coolie's bedroom",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall4,
    floor: OldWall,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 4,
    furniture: [
      FURNITURE.rug1,
      FURNITURE.fireplaceR,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.FF2_BT,
      FURNITURE.AA2_right,
      FURNITURE.FF3_left
    ],
    container: {
      furniture: FURNITURE.wardrobe1L,
      item: ITEMS.Acorn
    },
    items: [$.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.Shooter, ENEMIES.Devil]
  },
  room9: {
    id: 9,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: DungeonWall,
    floor: OldWall,
    ndoor: "blue1",
    edoor: "wood2",
    sdoor: "open",
    wdoor: null,
    nCon: 2,
    eCon: 10,
    sCon: 49,
    furniture: [
      FURNITURE.tapestry1L_HR,
      FURNITURE.lanternPole3LS,
      FURNITURE.lanternPole3RS,
      FURNITURE.lanternPole3L,
      FURNITURE.lanternPole3R,
      FURNITURE.lanternpole2EL_H,
      FURNITURE.lanternpole2ER_H
    ],
    enemy: [ENEMIES.Rambler],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room10: {
    id: 10,
    name: "the Knight's chamber",
    type: "indoor",
    grid: SquareRM,
    wall: OldWall,
    floor: BrickWall4,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 9,
    furniture: [
      FURNITURE.rug4,
      FURNITURE.tapestry3R,
      FURNITURE.PC_FF_TR,
      FURNITURE.wardrobe2L,
      FURNITURE.WallLamp_LL,
      FURNITURE.WallLamp_LR,
      FURNITURE.Pitfall2_BT,
      FURNITURE.Galaxian_left_L
    ],
    container: {
      furniture: FURNITURE.wardrobe2L,
      item: ITEMS.Lantern
    },
    player: PLAYERS.knight,
    alertFlag: true,
    alert:
      "The knight says: 'This castle is overrun with ghosts. I am so scared. If only I had a sword ...'",
    enemy: [ENEMIES.Rambler, ENEMIES.Hunter]
  },
  room11: {
    id: 11,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall,
    floor: RockFloor,
    ndoor: "wood1",
    edoor: "open",
    sdoor: "wood1",
    wdoor: null,
    nCon: 49,
    eCon: 12,
    sCon: 14,
    furniture: [
      FURNITURE.lanternPoleL,
      FURNITURE.lanternPoleR,
      FURNITURE.lanternPoleLS,
      FURNITURE.lanternPoleRS,
      FURNITURE.Pitfall_left_H_L,
      FURNITURE.WallLamp_RR_H,
      FURNITURE.WallLamp_RL_H
    ],
    enemy: [ENEMIES.Rambler],
    items: [$.extend(true, {}, ITEMS.ammo)]
    //items: [ITEMS.Crown] //for testing ENDING
  },
  room12: {
    id: 12,
    name: "the Castle entrance",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall3,
    floor: DungeonFloor2,
    wdoor: "blue2",
    ndoor: null,
    edoor: null,
    sdoor: "wood1",
    wCon: 11,
    sCon: 41,
    furniture: [
      FURNITURE.gate,
      FURNITURE.wallLamp_LT,
      FURNITURE.crack2L,
      FURNITURE.PC_FF_TL,
      FURNITURE.wallLamp_RT,
      FURNITURE.FF3_right,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.PAC2_left_L,
      FURNITURE.rug2,
      FURNITURE.Hero2_TR
    ],
    alertFlag: true,
    alert:
      "With a bang the gate closes behind your back. There is no going back ... Perhaps you should find something to store deadly yellow ghost repelling magic orbs?",
    items: [$.extend(true, {}, ITEMS.pouch)]
  },
  room13: {
    id: 13,
    name: "the Fruit storage",
    type: "indoor",
    grid: SquareRM,
    wall: WhiteWall,
    floor: Pavement2,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 7,
    furniture: [
      FURNITURE.PIC_DM_TC,
      FURNITURE.WallLamp_LL,
      FURNITURE.WallLamp_LR,
      FURNITURE.FF4_BT,
      FURNITURE.Aztec_right
    ],
    enemy: [ENEMIES.Hunter, ENEMIES.Hunter, ENEMIES.MirrorBoss],
    items: [$.extend(true, {}, ITEMS.health2), $.extend(true, {}, ITEMS.life)]
  },
  room14: {
    id: 14,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall4,
    floor: Pavement,
    ndoor: "open",
    edoor: null,
    sdoor: "blue1",
    wdoor: "wood2",
    nCon: 11,
    sCon: 21,
    wCon: 15,
    furniture: [
      FURNITURE.tree1_TRbD,
      FURNITURE.Phara_right_H,
      FURNITURE.TR8_left_H_L
    ],
    enemy: [ENEMIES.Rambler]
  },
  room15: {
    id: 15,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall2,
    floor: DungeonFloor,
    ndoor: null,
    edoor: "open",
    sdoor: "green",
    wdoor: "wood2",
    eCon: 14,
    wCon: 16,
    sCon: 17,
    furniture: [
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER,
      FURNITURE.tapestry4T_B,
      FURNITURE.DM3_BT_W_L
    ],
    enemy: [ENEMIES.Hunter],
    items: [ITEMS.Sword, $.extend(true, {}, ITEMS.health)]
  },
  room16: {
    id: 16,
    name: "the stable",
    type: "indoor",
    grid: SquareRM,
    wall: ThachFloor,
    floor: Grass,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 15,
    furniture: [
      FURNITURE.tree1_TR,
      FURNITURE.PC_WOW_TL,
      FURNITURE.HOB1_BT,
      FURNITURE.Galaxian_left,
      FURNITURE.Hay_left,
      FURNITURE.WallLamp_RR,
      FURNITURE.WallLamp_RL
    ],
    items: [
      $.extend(true, {}, ITEMS.pouch),
      ITEMS.Fly,
      $.extend(true, {}, ITEMS.ammo)
    ],
    enemy: [ENEMIES.Hunter, ENEMIES.Rambler]
  },
  room17: {
    id: 17,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall2,
    floor: StoneFloor2,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: "wood2",
    nCon: 15,
    wCon: 20,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.Knightlore_BT,
      FURNITURE.Amber_right_H
    ],
    enemy: [ENEMIES.Rambler, ENEMIES.ZombieGirl],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room18: {
    id: 18,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall2,
    floor: StoneFloor4,
    ndoor: "wood1",
    edoor: "open",
    sdoor: null,
    wdoor: "orange2",
    nCon: 19,
    eCon: 50,
    wCon: 28,
    furniture: [FURNITURE.wallLamp_LT, FURNITURE.wallLamp_RT, FURNITURE.FF4_BT],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health2)],
    enemy: [ENEMIES.Death1]
  },
  room19: {
    id: 19,
    name: "the Pond cavern",
    type: "indoor",
    grid: SquareRM,
    wall: StrangeWall,
    floor: Grass,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 18,
    furniture: [
      FURNITURE.pond,
      FURNITURE.Frogger_TR,
      FURNITURE.tree2_TL,
      FURNITURE.tree1_TLbD,
      FURNITURE.Invaders_left,
      FURNITURE.Pitfall3_right,
      FURNITURE.openGateS
    ],
    items: [ITEMS.Frog],
    enemy: [ENEMIES.Death1, ENEMIES.Hunter, ENEMIES.Hunter]
  },
  room20: {
    id: 20,
    name: "the Witch's room",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: StoneFloor3,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 17,
    furniture: [
      FURNITURE.cauldron,
      FURNITURE.crack1_TR,
      FURNITURE.crack2,
      FURNITURE.PC_WOW_TR,
      FURNITURE.Lode_left,
      FURNITURE.rug1,
      FURNITURE.torch_RL,
      FURNITURE.torch_RR
    ],
    player: PLAYERS.witch,
    items: [],
    alertFlag: true,
    alert:
      "The witch says: 'I need a mouse, a frog and a mushroom for my magic potion. Find them for me.'",
    enemy: [
      ENEMIES.Rambler,
      ENEMIES.Rambler,
      ENEMIES.Rambler,
      ENEMIES.RamblingSnake
    ]
  },
  room21: {
    id: 21,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall3,
    floor: DungeonFloor,
    ndoor: "open",
    edoor: null,
    sdoor: "orange1",
    wdoor: null,
    nCon: 14,
    sCon: 22,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.AA5_left_H_L,
      FURNITURE.DM3_right_H_L
    ],
    items: [ITEMS.Coin5],
    enemy: [ENEMIES.Hunter]
  },
  room22: {
    id: 22,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: SlateWall,
    floor: BrickWall,
    ndoor: "open",
    edoor: "wood2",
    sdoor: "wood1",
    wdoor: null,
    nCon: 21,
    sCon: 23,
    eCon: 39,
    furniture: [
      FURNITURE.torch_H_RL,
      FURNITURE.torch_H_RR,
      FURNITURE.LTUT_left_H,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Snake, ENEMIES.Snake]
  },
  room23: {
    id: 23,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneFloor,
    floor: OldWall,
    ndoor: "open",
    edoor: null,
    sdoor: "wood1",
    wdoor: null,
    nCon: 22,
    sCon: 24,
    furniture: [
      FURNITURE.AA3_right_H,
      FURNITURE.DM3_left_H_R,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Snake, ENEMIES.SnakeHunter],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health)]
  },
  room24: {
    id: 24,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: YellowBrick,
    floor: BrokenRuin,
    ndoor: "open",
    edoor: "wood2",
    sdoor: "silver1",
    wdoor: "silver2",
    nCon: 23,
    sCon: 25,
    eCon: 29,
    wCon: 94,
    furniture: [
      FURNITURE.lanternpole2EL_H,
      FURNITURE.lanternpole2ER_H,
      FURNITURE.Tut_left_H_up,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.SnakeHunter, ENEMIES.SnakeHunter],
    items: [$.extend(true, {}, ITEMS.health)]
  },
  room25: {
    id: 25,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall2,
    floor: StoneFloor4,
    ndoor: "open",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 24,
    sCon: 26,
    furniture: [
      FURNITURE.torch_H_RR,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.Pitfall2_right_H,
      FURNITURE.sign,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Devil, ENEMIES.Devil, ENEMIES.Devil],
    items: [
      $.extend(true, {}, ITEMS.health),
      $.extend(true, {}, ITEMS.health),
      $.extend(true, {}, ITEMS.ammo)
    ]
  },
  room26: {
    id: 26,
    name: "the Treasury",
    type: "indoor",
    grid: SquareRM,
    wall: CastleWall,
    floor: BrokenRuin,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 25,
    furniture: [
      FURNITURE.AA3_TL,
      FURNITURE.Knightlore_TR,
      FURNITURE.Gold2,
      FURNITURE.PAC2_right,
      FURNITURE.Invaders_BT,
      FURNITURE.Aztec_left,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    container: {
      furniture: FURNITURE.Gold1,
      item: ITEMS.GoldBar4
    },
    enemy: [
      ENEMIES.Death1,
      ENEMIES.Death2,
      ENEMIES.Death1,
      ENEMIES.Death2,
      ENEMIES.Death11,
      ENEMIES.Death22,
      ENEMIES.ZombieQuick
    ]
  },
  room27: {
    id: 27,
    name: "the Bear's place",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: ThachFloor,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 6,
    furniture: [
      FURNITURE.PC_SVS_TC,
      FURNITURE.tree1_TR,
      FURNITURE.tree1_TL,
      FURNITURE.FF3_right,
      FURNITURE.AA5_BT,
      FURNITURE.WallLamp_LL,
      FURNITURE.WallLamp_LR
    ],
    items: [$.extend(true, {}, ITEMS.ammo), ITEMS.Mushroom],
    enemy: [ENEMIES.Shooter, ENEMIES.Hunter],
    player: PLAYERS.bear,
    alert: "The bear seems hungry ...",
    alertFlag: true
  },
  room28: {
    id: 28,
    name: "the Henhouse",
    type: "indoor",
    grid: SquareRM,
    wall: Gravel,
    floor: Grass,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 18,
    wCon: 30,
    furniture: [
      FURNITURE.plant2_TR,
      FURNITURE.plant3_TL,
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER,
      FURNITURE.torch_LL,
      FURNITURE.torch_LR,
      FURNITURE.Knightlore_BT,
      FURNITURE.Prince_TC,
      FURNITURE.Arena_right_R
    ],
    enemy: [ENEMIES.Devil, ENEMIES.Devil, ENEMIES.Devil],
    items: [$.extend(true, {}, ITEMS.health2), $.extend(true, {}, ITEMS.health)]
  },
  room29: {
    id: 29,
    name: "the Faerie's",
    type: "indoor",
    grid: SquareRM,
    wall: OldWall,
    floor: StoneFloor,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 24,
    furniture: [
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR,
      FURNITURE.PIC_DM2_TR,
      FURNITURE.plant1_TL,
      FURNITURE.SVS_right,
      FURNITURE.RRR_BT,
      FURNITURE.Penta_left_L,
      FURNITURE.LSL1_left_R
    ],
    player: PLAYERS.faerie,
    alertFlag: true,
    alert:
      "The faerie says: 'I will be the new princess. I need a hat and a necklace. Also, one skeleton stole my hand mirror. I need my hand mirror to observe my beauty.'",
    items: [$.extend(true, {}, ITEMS.health), $.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.Skeleton, ENEMIES.Skeleton]
  },
  room30: {
    id: 30,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall,
    floor: DungeonFloor,
    ndoor: null,
    edoor: "open",
    sdoor: "wood1",
    wdoor: null,
    eCon: 28,
    sCon: 31,
    furniture: [
      FURNITURE.PIC_DM3_BC,
      FURNITURE.FF3_left,
      FURNITURE.clock_W_TL,
      FURNITURE.wallLamp_BL_W,
      FURNITURE.wallLamp_BR_W
    ],
    enemy: [ENEMIES.Death22],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room31: {
    id: 31,
    name: "the Ghost's room",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall3,
    floor: StoneFloor3,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 30,
    furniture: [
      FURNITURE.cauldron2,
      FURNITURE.rug5,
      FURNITURE.Apshai_left,
      FURNITURE.Scramble_BT,
      FURNITURE.Under_right,
      FURNITURE.openGate
    ],
    player: PLAYERS.ghost,
    alertFlag: true,
    alert:
      "The ghost says: 'I am afraid. It's so dark. So many hostile ghosts in the castle. It's haunted. If I only had a lantern. I would change it for this necklace I found.'",
    enemy: [ENEMIES.Death22, ENEMIES.Death11, ENEMIES.Shooter],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health3)]
  },
  room32: {
    id: 32,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall2,
    floor: StoneFloor4,
    ndoor: "wood1",
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 6,
    wCon: 33,
    nCon: 34,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.lanternpole2WL_H,
      FURNITURE.lanternpole2WR_H,
      FURNITURE.Frogger_BT,
      FURNITURE.DM5_right_H_R,
      FURNITURE.DM3_right_H_L
    ],
    enemy: [ENEMIES.Rambler]
  },
  room33: {
    id: 33,
    name: "the dusty storage",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall2,
    floor: BrickWall,
    ndoor: null,
    wdoor: null,
    sdoor: null,
    edoor: "open",
    eCon: 32,
    furniture: [
      FURNITURE.tallClock_TR,
      FURNITURE.PC_Hero_TC,
      FURNITURE.rug6,
      FURNITURE.Prince_BT,
      FURNITURE.Galaxian_left,
      FURNITURE.WallLamp_RR,
      FURNITURE.WallLamp_RL
    ],
    container: {
      furniture: FURNITURE.chest,
      item: ITEMS.Coin3
    },
    enemy: [ENEMIES.Rambler, ENEMIES.Hunter, ENEMIES.ZombieGirl],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room34: {
    id: 34,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: CastleWall,
    floor: StoneFloor2,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: "wood2",
    sCon: 32,
    nCon: 35,
    wCon: 37,
    furniture: [FURNITURE.spiderWeb_HR, FURNITURE.Pitfall2_right_H],
    items: [$.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.ZombieGirl, ENEMIES.ZombieGirl]
  },
  room35: {
    id: 35,
    name: "the Spider's web",
    type: "indoor",
    grid: SquareRM,
    wall: WhiteWall,
    floor: StoneFloor,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: "wood2",
    sCon: 34,
    wCon: 36,
    furniture: [
      FURNITURE.spiderWeb,
      FURNITURE.Dig_right,
      FURNITURE.Pitfall2_left_L,
      FURNITURE.DK_left_R,
      FURNITURE.Aztec_BT_R,
      FURNITURE.FF4_TC,
      FURNITURE.spiderWeb_L
    ],
    player: PLAYERS.spider,
    enemy: [ENEMIES.Rambler, ENEMIES.Hunter],
    alertFlag: true,
    alert: "The spider seems famished ..."
  },
  room36: {
    id: 36,
    name: "the Spider's storage",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall,
    floor: StoneFloor4,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 35,
    furniture: [
      FURNITURE.Lode_TC,
      FURNITURE.spiderWeb,
      FURNITURE.spiderWeb_C,
      FURNITURE.spiderWeb_L,
      FURNITURE.JSW_left,
      FURNITURE.Hero_BT,
      FURNITURE.WallLamp_RR,
      FURNITURE.WallLamp_RL
    ],
    player: PLAYERS.skeleton,
    enemy: [ENEMIES.Rambler, ENEMIES.Shooter, ENEMIES.Hunter],
    alertFlag: true,
    alert:
      "The skeleton says; 'I will sell my little friend for 5 gold pieces.'"
  },
  room37: {
    id: 37,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall,
    floor: DungeonFloor2,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 34,
    wCon: 38,
    furniture: [
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER,
      FURNITURE.tapestry4T_B,
      FURNITURE.Tut2_BT_W
    ],
    enemy: [ENEMIES.Skeleton]
  },
  room38: {
    id: 38,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall4,
    floor: DungeonWall2,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 37,
    wCon: 40,
    furniture: [
      FURNITURE.PIC_Hobbit_BC,
      FURNITURE.tallClock_BR,
      FURNITURE.tree2_BL,
      FURNITURE.Tut_BT_W
    ],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room39: {
    id: 39,
    name: "the dusty storage",
    type: "indoor",
    grid: SquareRM,
    wall: OldWall,
    floor: Pavement2,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 22,
    furniture: [
      FURNITURE.rug2,
      FURNITURE.fireplaceC,
      FURNITURE.PIC_AA_TL,
      FURNITURE.AA4_BT,
      FURNITURE.Tut2_right,
      FURNITURE.DM5_left_L,
      FURNITURE.SW2_left_R,
      FURNITURE.WallLamp_RR,
      FURNITURE.WallLamp_RL,
      FURNITURE.openGateW
    ],
    container: {
      furniture: FURNITURE.wardrobe2R,
      item: ITEMS.Hat
    },
    enemy: [ENEMIES.Skeleton, ENEMIES.Skeleton, ENEMIES.Skeleton]
  },
  room40: {
    id: 40,
    name: "the Wolf's den",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall,
    floor: YellowBrick,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 38,
    furniture: [
      FURNITURE.clock_TR,
      FURNITURE.PC_FF_TC,
      FURNITURE.tree1_TL,
      FURNITURE.tapestry6L_R,
      FURNITURE.SheepSkinRug,
      FURNITURE.HOB2_BT,
      FURNITURE.DK_right_R,
      FURNITURE.openGateE
    ],
    enemy: [ENEMIES.CoinBoss, ENEMIES.Hunter, ENEMIES.Hunter],
    items: [
      $.extend(true, {}, ITEMS.pouch),
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.health)
    ]
  },
  room41: {
    id: 41,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall,
    floor: StoneFloor4,
    ndoor: "open",
    edoor: null,
    sdoor: "wood1",
    wdoor: null,
    nCon: 12,
    sCon: 42,
    furniture: [
      FURNITURE.Apshai_left_H,
      FURNITURE.AA4_right_H,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Rambler],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room42: {
    id: 42,
    name: "the kennel",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall,
    floor: StoneFloor3,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 41,
    furniture: [
      FURNITURE.PIC_AA_TR,
      FURNITURE.DM1_left,
      FURNITURE.Lode_right,
      FURNITURE.rug6,
      FURNITURE.Prince_BT,
      FURNITURE.Pitfall_TL,
      FURNITURE.openGate
    ],
    enemy: [ENEMIES.Rambler, ENEMIES.Rambler],
    items: [ITEMS.blueKey]
  },
  room43: {
    id: 43,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall4,
    floor: StoneFloor3,
    ndoor: null,
    edoor: "wood2",
    sdoor: null,
    wdoor: "open",
    eCon: 44,
    wCon: 2,
    furniture: [FURNITURE.bush_BL, FURNITURE.FF2_BR, FURNITURE.Apshai_W_BL],
    enemy: [ENEMIES.Death1, ENEMIES.Death11]
  },
  room44: {
    id: 44,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall2,
    floor: StoneFloor,
    ndoor: null,
    edoor: "wood2",
    sdoor: null,
    wdoor: "open",
    eCon: 45,
    wCon: 43,
    furniture: [FURNITURE.Prince_TDR, FURNITURE.Tut_TDL, FURNITURE.HOB2_W_BT],
    enemy: [ENEMIES.Death2]
  },
  room45: {
    id: 45,
    name: "Way Down",
    type: "indoor",
    grid: SquareRM,
    wall: BlackBrickWall,
    floor: TlakFloor,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 44,
    nCon: 51,
    furniture: [
      FURNITURE.Galaxian_BC,
      FURNITURE.Pitfall3_right,
      FURNITURE.torch_LL,
      FURNITURE.torch_LR,
      FURNITURE.openGate,
      FURNITURE.VIXEN_TC,
      FURNITURE.GRB_TR
    ],
    items: [
      $.extend(true, {}, ITEMS.pouch),
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.life)
    ],
    enemy: [ENEMIES.Death1, ENEMIES.Death11, ENEMIES.Death111]
  },
  room46: {
    id: 46,
    name: "staircase",
    type: "stair",
    grid: StairRM,
    wall: DungeonWall2,
    floor: StoneFloor3,
    ndoor: "open",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 0,
    sCon: 47,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.wallLamp_BL,
      FURNITURE.wallLamp_BR
    ]
  },
  room47: {
    id: 47,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall3,
    floor: DungeonWall2,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: "pink2",
    nCon: 46,
    wCon: 68,
    furniture: [
      FURNITURE.tallClock_BR,
      FURNITURE.LSL2_TL_W,
      FURNITURE.SVS4_right,
      FURNITURE.MOON_BT_CW
    ],
    items: [$.extend(true, {}, ITEMS.health), $.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.Skelleton8, ENEMIES.Skelleton8, ENEMIES.Skelleton8]
  },
  room48: {
    id: 48,
    name: "outside",
    type: "outdoor",
    grid: SquareRM,
    wall: HedgeWall,
    nwall: HedgeWall,
    ewall: HedgeWall,
    wwall: HedgeWall,
    swall: BrickWall3,
    floor: Grass,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 12,
    furniture: [
      FURNITURE.bush_TR,
      FURNITURE.tree1_TL,
      FURNITURE.tree1_TL2,
      FURNITURE.tree2_TR,
      FURNITURE.openGateS,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR
    ],
    items: [$.extend(true, {}, ITEMS.health)],
    player: PLAYERS.princess,
    alertFlag: true,
    alert:
      "The Princess says: 'You are the only one who can help me. Enter the castle, find my crown and bring it out to me. Now. Hurry.'"
  },
  room49: {
    id: 49,
    name: "staircase",
    type: "stair",
    grid: StairRM,
    wall: DungeonWall,
    floor: StoneFloor,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 9,
    sCon: 11,
    furniture: []
  },
  room50: {
    id: 50,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BrickWall3,
    floor: StoneFloor2,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 5,
    wCon: 18,
    furniture: [
      FURNITURE.PIC_FRED_TC_W,
      FURNITURE.ZX_BC_W,
      FURNITURE.WallLamp_LL,
      FURNITURE.WallLamp_LR
    ]
  },
  room51: {
    id: 51,
    type: "stair",
    grid: StairRM,
    wall: BrickWall4,
    floor: BlackWall,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 45,
    nCon: 52,
    furniture: [
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ]
  },
  room52: {
    id: 52,
    name: "staircase",
    type: "stair",
    grid: StairRM,
    wall: StoneWall5,
    floor: LavaWall,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 51,
    nCon: 53,
    furniture: [FURNITURE.wallLamp_LT, FURNITURE.wallLamp_RT]
  },
  room53: {
    id: 53,
    name: "Reaper's",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall4,
    floor: LavaWall2,
    ndoor: "pink1",
    edoor: "wood2",
    sdoor: "open",
    wdoor: "wood2",
    sCon: 52,
    wCon: 54,
    eCon: 58,
    nCon: 67,
    furniture: [
      FURNITURE.openGateS,
      FURNITURE.ZX_TL,
      FURNITURE.WALLSKELL1_R,
      FURNITURE.WALLSKELL2_L,
      FURNITURE.Penta_left_L,
      FURNITURE.BlueMax_right_R
    ],
    player: PLAYERS.reaper,
    alertFlag: true,
    alert: "I am owed three souls. I am not leaving before I get them.",
    enemy: [ENEMIES.Death1, ENEMIES.Skeleton5, ENEMIES.Skeleton5],
    items: [$.extend(true, {}, ITEMS.time)]
  },
  room54: {
    id: 54,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: BrickWall5,
    floor: BrokenRuin,
    ndoor: "wood1",
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 53,
    nCon: 55,
    furniture: [
      FURNITURE.lanternpole2EL_H,
      FURNITURE.lanternpole2ER_H,
      FURNITURE.Tut_left_H,
      FURNITURE.MANIAC_BT_C
    ],
    items: [$.extend(true, {}, ITEMS.health), $.extend(true, {}, ITEMS.ammo)],
    enemy: [ENEMIES.Ugly]
  },
  room55: {
    id: 55,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall,
    floor: TileFloor,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 56,
    sCon: 54,
    furniture: [
      FURNITURE.Sabre3_left_L_H,
      FURNITURE.SKI_right_R_H,
      FURNITURE.WALLSKELL2_LH
    ],
    enemy: [ENEMIES.Death1],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room56: {
    id: 56,
    name: "a hallway",
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall3,
    floor: StoneFloor5,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 57,
    sCon: 55,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.LSL2_right_L_H,
      FURNITURE.LSL1_left_R_H
    ],
    enemy: [ENEMIES.ZombieGirl, ENEMIES.Skelleton8],
    items: []
  },
  room57: {
    id: 57,
    name: "Soul1",
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall4,
    floor: TlakFloor3,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 56,
    furniture: [
      FURNITURE.WALLSKELL1_R,
      FURNITURE.WALLSKELL2_LH,
      FURNITURE.CAVELON_TC,
      FURNITURE.TRASH_BR,
      FURNITURE.LTUT_right_R,
      FURNITURE.TR1_left,
      FURNITURE.openGateS
    ],
    enemy: [
      ENEMIES.Devil,
      ENEMIES.Death2,
      ENEMIES.Skeleton7,
      ENEMIES.Death2,
      ENEMIES.SoulBoss1
    ],
    items: [$.extend(true, {}, ITEMS.health3)],
    container: {
      furniture: FURNITURE.Sarcophagus,
      item: ITEMS.speed
    }
  },
  room58: {
    id: 58,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: StoneFloor5,
    floor: Pavement2,
    ndoor: null,
    edoor: "yellow1",
    sdoor: null,
    wdoor: "open",
    eCon: 59,
    wCon: 53,
    furniture: [
      FURNITURE.clock_W_TL,
      FURNITURE.Miner_BT_R_W,
      FURNITURE.EOB1_TC_W,
      FURNITURE.FF2_BT_L_W
    ],
    enemy: [ENEMIES.Devil],
    items: [$.extend(true, {}, ITEMS.health2), $.extend(true, {}, ITEMS.ammo)]
  },
  room59: {
    id: 59,
    name: "Intersection",
    type: "indoor",
    grid: SquareRM,
    wall: Pavement,
    floor: TlakFloor4,
    ndoor: "wood1",
    edoor: "wood2",
    sdoor: "wood1",
    wdoor: "open",
    wCon: 58,
    sCon: 60,
    nCon: 61,
    eCon: 63,
    furniture: [
      FURNITURE.rug1,
      FURNITURE.TR1_TL,
      FURNITURE.SORCERY_TR,
      FURNITURE.RRR_BT_R,
      FURNITURE.LSL6_left_L,
      FURNITURE.wallLamp_LL,
      FURNITURE.wallLamp_LR,
      FURNITURE.wallLamp_RR,
      FURNITURE.wallLamp_RL
    ],
    enemy: [ENEMIES.Devil, ENEMIES.Death22, ENEMIES.Death11, ENEMIES.Death1],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.ammo)]
  },
  room60: {
    id: 60,
    name: "DeadEnd",
    type: "indoor",
    grid: SquareRM,
    wall: ThachFloor,
    floor: TlakFloor,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 59,
    furniture: [
      FURNITURE.LSL1_TR,
      FURNITURE.EOB1_right,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.Sorcery_left,
      FURNITURE.PITFALL_BT_C
    ],
    enemy: [ENEMIES.ZombieGirl, ENEMIES.Death2, ENEMIES.ZombieGirl2],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.ammo)],
    container: {
      furniture: FURNITURE.chest,
      item: $.extend(true, {}, ITEMS.pouch)
    }
  },
  room61: {
    id: 61,
    name: "wide corridor",
    type: "indoor",
    grid: SquareRM,
    wall: RockFloor,
    floor: TlakFloor3,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 62,
    sCon: 59,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.BLUEMAX_TL,
      FURNITURE.SKI_TR,
      FURNITURE.Fred_left,
      FURNITURE.Cavelon_BR,
      FURNITURE.Castle_right
    ],
    enemy: [ENEMIES.ZombieGirl, ENEMIES.ZombieGirl2, ENEMIES.ZombieGirl3],
    items: [
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.bomb)
    ]
  },
  room62: {
    id: 62,
    name: "Soul2",
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor3,
    floor: DungeonWall2,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 61,
    furniture: [
      FURNITURE.TR2_TC,
      FURNITURE.Valhalla_right,
      FURNITURE.clock_TL,
      FURNITURE.spiderWeb,
      FURNITURE.crack2L,
      FURNITURE.Manic_BR,
      FURNITURE.TR3_left,
      FURNITURE.openGateS
    ],
    enemy: [
      ENEMIES.SoulBoss2,
      ENEMIES.Death1,
      ENEMIES.Death11,
      ENEMIES.Skeleton5
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health)]
  },
  room63: {
    id: 63,
    name: "wide corridor",
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor4,
    floor: YellowBrick,
    ndoor: null,
    edoor: "wood2",
    sdoor: null,
    wdoor: "open",
    wCon: 59,
    eCon: 64,
    furniture: [
      FURNITURE.EOB2_TC,
      FURNITURE.DM7_BT_C,
      FURNITURE.Fred2_left_L,
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER,
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR,
      FURNITURE.Pitfall2_right_R
    ],
    enemy: [ENEMIES.Devil, ENEMIES.ZombieGirl3, ENEMIES.Skelleton8],
    items: [$.extend(true, {}, ITEMS.time), $.extend(true, {}, ITEMS.ammo)]
  },
  room64: {
    id: 64,
    name: "wide corridor",
    type: "indoor",
    grid: SquareRM,
    wall: YellowBrick,
    floor: DungeonFloor,
    ndoor: null,
    edoor: null,
    sdoor: "wood1",
    wdoor: "open",
    wCon: 63,
    sCon: 65,
    furniture: [
      FURNITURE.SVS4_TC,
      FURNITURE.fireplaceL,
      FURNITURE.fireplaceR,
      FURNITURE.rug2,
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.GRB_right
    ],
    enemy: [
      ENEMIES.Skeleton5,
      ENEMIES.Skeleton,
      ENEMIES.Death2,
      ENEMIES.Skelleton8
    ],
    items: []
  },
  room65: {
    id: 65,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: Pavement2,
    floor: StoneFloor2,
    ndoor: "open",
    edoor: "wood2",
    sdoor: null,
    wdoor: null,
    nCon: 64,
    eCon: 66,
    furniture: [
      FURNITURE.GRB_BT_CW,
      FURNITURE.MOON_TL_W,
      FURNITURE.IM_TR_W,
      FURNITURE.UU_left
    ],
    enemy: [ENEMIES.Devil, ENEMIES.Death1],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.ammo)]
  },
  room66: {
    id: 66,
    name: "Soul3",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: SlateWall,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 65,
    furniture: [
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR,
      FURNITURE.GRB_left_L,
      FURNITURE.GRB_left_R,
      FURNITURE.MONKEY_BT_C,
      FURNITURE.CASTLE_TL,
      FURNITURE.EOB3_TR,
      FURNITURE.WINTER_right
    ],
    enemy: [
      ENEMIES.SoulBoss3,
      ENEMIES.Skeleton,
      ENEMIES.Skeleton7,
      ENEMIES.Skeleton5,
      ENEMIES.Death1
    ],
    items: [$.extend(true, {}, ITEMS.health2), $.extend(true, {}, ITEMS.life)]
  },
  room67: {
    id: 67,
    name: "what?",
    type: "indoor",
    grid: SquareRM,
    wall: SlateWall,
    floor: LavaWall,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 53,
    furniture: [
      FURNITURE.openGateS,
      FURNITURE.LSL4_TR,
      FURNITURE.EOB3_right,
      FURNITURE.GRB_TC,
      FURNITURE.rug3,
      FURNITURE.Monkey_left,
      FURNITURE.TR2_BR,
      FURNITURE.Galaxian_BL
    ],
    enemy: [ENEMIES.Death1, ENEMIES.Death1, ENEMIES.Death2, ENEMIES.Death2],
    items: [$.extend(true, {}, ITEMS.health), $.extend(true, {}, ITEMS.ammo)],
    container: {
      furniture: FURNITURE.chest,
      item: ITEMS.Ring1
    }
  },
  room68: {
    id: 68,
    name: "a hallway",
    type: "indoor",
    grid: WRectRM,
    wall: BlackBrickWall2,
    floor: StoneWall,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 47,
    wCon: 69,
    furniture: [FURNITURE.Fred2_TC_W, FURNITURE.IM_BT_CW],
    enemy: [
      ENEMIES.Skeleton,
      ENEMIES.Skeleton,
      ENEMIES.Skeleton,
      ENEMIES.Skeleton
    ]
  },
  room69: {
    id: 69,
    name: "Gandalf",
    type: "indoor",
    grid: SquareRM,
    wall: BrokenRuin,
    floor: TlakFloor4b,
    ndoor: null,
    edoor: "open",
    sdoor: "wood1",
    wdoor: null,
    eCon: 68,
    sCon: 70,
    furniture: [
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.Monkey_TR,
      FURNITURE.TR3_TL,
      FURNITURE.LSL4_left,
      FURNITURE.C64_right_R,
      FURNITURE.Hero_BT_L
    ],
    enemy: [
      ENEMIES.ZombieGirl3,
      ENEMIES.Hunter,
      ENEMIES.Rambler,
      ENEMIES.Skeleton7
    ],
    items: [
      $.extend(true, {}, ITEMS.health2),
      $.extend(true, {}, ITEMS.health2),
      $.extend(true, {}, ITEMS.health2),
      $.extend(true, {}, ITEMS.life)
    ],
    player: PLAYERS.cat,
    alertFlag: true,
    alert:
      "The cat says:'I will become the greatest wizard of them all. I just need three rings of power. I know my master took one. He is off hiding somewhere.'"
  },
  room70: {
    id: 70,
    name: "staircase",
    type: "stair",
    grid: StairRM,
    wall: StoneWall2,
    floor: LavaWall2,
    ndoor: "open",
    edoor: null,
    sdoor: "wood1",
    wdoor: null,
    sCon: 71,
    nCon: 69,
    furniture: [
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.torch_TL,
      FURNITURE.torch_TR
    ]
  },
  room71: {
    id: 71,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: CastleWall,
    floor: OldWall,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: "wood2",
    nCon: 70,
    wCon: 72,
    furniture: [
      FURNITURE.torch_TL,
      FURNITURE.torch_TR,
      FURNITURE.rug6,
      FURNITURE.LSL3_TR,
      FURNITURE.Kara_TL,
      FURNITURE.MANIAC_BT_C,
      FURNITURE.HOB5_right,
      FURNITURE.torch1_LL,
      FURNITURE.torch1_LR
    ],
    enemy: [
      ENEMIES.Hunter,
      ENEMIES.RamblingSnake,
      ENEMIES.RamblingSnake,
      ENEMIES.DevilBlue,
      ENEMIES.Death2,
      ENEMIES.Death111
    ],
    items: [$.extend(true, {}, ITEMS.health)]
  },
  room72: {
    id: 72,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall7,
    floor: BrickWall,
    ndoor: null,
    edoor: "open",
    sdoor: "blue1",
    wdoor: "wood2",
    eCon: 71,
    wCon: 73,
    sCon: 80,
    furniture: [
      FURNITURE.DM7_TL,
      FURNITURE.Sabre2_TR,
      FURNITURE.EOB4_TC,
      FURNITURE.Eric_BT_L,
      FURNITURE.ST_left_L,
      FURNITURE.rug4,
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER
    ],
    enemy: [
      ENEMIES.Death1,
      ENEMIES.Death222,
      ENEMIES.Skelleton8,
      ENEMIES.Zombiehunter
    ],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.life)],
    container: {
      furniture: FURNITURE.Sarcophagus,
      item: ITEMS.speed
    }
  },
  room73: {
    id: 73,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: BrickWall2,
    floor: BrokenRuin,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 72,
    wCon: 74,
    furniture: [
      FURNITURE.Vixen2_TR,
      FURNITURE.Falcon_TL,
      FURNITURE.Ultima1_BT_C
    ],
    enemy: [
      ENEMIES.Zombiehunter,
      ENEMIES.SkeletonHunter,
      ENEMIES.SkeletonHunter,
      ENEMIES.Zombiehunter
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.bomb)]
  },
  room74: {
    id: 74,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall,
    floor: BrokenRuin,
    ndoor: "wood1",
    edoor: "open",
    sdoor: null,
    wdoor: "silver2",
    eCon: 73,
    nCon: 75,
    wCon: 83,
    furniture: [
      FURNITURE.LSL7_TL,
      FURNITURE.LSL6_TR,
      FURNITURE.Ultima2_left_L,
      FURNITURE.AA7_right_R,
      FURNITURE.FF2_BT,
      FURNITURE.torch_TL,
      FURNITURE.torch_TR
    ],
    enemy: [
      ENEMIES.ZombieGirl3,
      ENEMIES.ZombieGirl3,
      ENEMIES.ZombieGirl3,
      ENEMIES.Death1
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health)]
  },
  room75: {
    id: 75,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: StoneFloor5,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 76,
    sCon: 74,
    furniture: [
      FURNITURE.lanternPole3LS,
      FURNITURE.lanternPole3RS,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.UU_TR,
      FURNITURE.Walls_TL,
      FURNITURE.AA9_right,
      FURNITURE.Bagitman_left,
      FURNITURE.GRB_BL,
      FURNITURE.GRB_BR
    ],
    enemy: [
      ENEMIES.SkeletonHunter3,
      ENEMIES.SkeletonHunter3,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter,
      ENEMIES.Zombiehunter
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health3)],
    container: {
      furniture: FURNITURE.Sarcophagus,
      item: $.extend(true, {}, ITEMS.pouch)
    }
  },
  room76: {
    id: 76,
    name: "fight",
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall3,
    floor: RockWall,
    ndoor: null,
    edoor: "open",
    sdoor: "open",
    wdoor: "wood2",
    eCon: 77,
    wCon: 78,
    sCon: 75,
    furniture: [
      FURNITURE.tapestry6R_R,
      FURNITURE.wallLamp_LL,
      FURNITURE.wallLamp_LR,
      FURNITURE.wallLamp_RR_gandalf,
      FURNITURE.wallLamp_RL_gandalf,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.SVS6_TL,
      FURNITURE.Hero2_TR,
      FURNITURE.ST_left_L
    ],
    enemy: [
      ENEMIES.SkeletonHunter3,
      ENEMIES.SkeletonHunter3,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter,
      ENEMIES.Zombiehunter
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health2)]
  },
  room77: {
    id: 77,
    name: "secret room",
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall4,
    floor: SlateWall,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 76,
    furniture: [
      FURNITURE.Amber_TR,
      FURNITURE.Horace_TL,
      FURNITURE.wallLamp_LL,
      FURNITURE.wallLamp_LR,
      FURNITURE.Hunch_left_L,
      FURNITURE.AA7_right_R,
      FURNITURE.Wow3_BT
    ],
    enemy: [
      ENEMIES.Gandalf,
      ENEMIES.ZombieGirl,
      ENEMIES.ZombieGirl2,
      ENEMIES.Skeleton7,
      ENEMIES.ZombieGirl3,
      ENEMIES.Skeleton7
    ],
    items: [
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.life),
      $.extend(true, {}, ITEMS.ammo)
    ]
  },
  room78: {
    id: 78,
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall3b,
    floor: YellowBrick,
    ndoor: "wood1",
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 76,
    nCon: 79,
    furniture: [
      FURNITURE.wallLamp_RR,
      FURNITURE.wallLamp_RL,
      FURNITURE.Hunch_BT_C,
      FURNITURE.AMC_left,
      FURNITURE.Wow3_TL,
      FURNITURE.Bagitman_TR
    ],
    enemy: [
      ENEMIES.DragonHunter,
      ENEMIES.DragonHunter,
      ENEMIES.DragonHunter,
      ENEMIES.DragonShooter,
      ENEMIES.Ugly
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.time)]
  },
  room79: {
    id: 79,
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall,
    floor: DungeonFloor2,
    ndoor: "gold1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 78,
    nCon: 96,
    furniture: [
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.Amber_right,
      FURNITURE.UU_left,
      FURNITURE.GRB_BL,
      FURNITURE.GRB_BR,
      FURNITURE.Hunch_TR,
      FURNITURE.C64_TL,
      FURNITURE.Gold2
    ],
    enemy: [ENEMIES.DragonHunter, ENEMIES.DragonHunter, ENEMIES.DragonHunter2],
    items: [],
    player: PLAYERS.dragon,
    alertFlag: true,
    alert: "The dragon says: 'I want more gold. I need five more bars!'",
    container: {
      furniture: FURNITURE.Gold1,
      item: ITEMS.GoldBar1
    }
  },
  room80: {
    id: 80,
    type: "indoor",
    grid: HRectRM,
    wall: StoneWall2,
    floor: DungeonFloor,
    ndoor: "open",
    edoor: null,
    sdoor: "wood1",
    wdoor: null,
    sCon: 81,
    nCon: 72,
    furniture: [
      FURNITURE.TR5_left_H,
      FURNITURE.EOB2_right_H,
      FURNITURE.wallLamp_BL,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Death111, ENEMIES.Death222],
    items: []
  },
  room81: {
    id: 81,
    type: "indoor",
    grid: WRectRM,
    wall: StrangeWall,
    floor: ThachFloor,
    ndoor: "open",
    edoor: "wood2",
    sdoor: "wood1",
    wdoor: null,
    nCon: 80,
    eCon: 82,
    sCon: 85,
    furniture: [
      FURNITURE.HOB4_left,
      FURNITURE.wallLamp_LT_W,
      FURNITURE.wallLamp_RT_W,
      FURNITURE.Valhalla_TL_W,
      FURNITURE.Manic_TR_W
    ],
    enemy: [ENEMIES.Death1],
    items: [$.extend(true, {}, ITEMS.ammo)]
  },
  room82: {
    id: 82,
    type: "indoor",
    grid: SquareRM,
    wall: ThachFloor,
    floor: LavaWall,
    ndoor: null,
    edoor: null,
    sdoor: null,
    wdoor: "open",
    wCon: 81,
    furniture: [
      FURNITURE.Miner_TR,
      FURNITURE.Winter_TL,
      FURNITURE.IM_right,
      FURNITURE.TR4_BT_C,
      FURNITURE.lanternpole2WL,
      FURNITURE.lanternpole2WR
    ],
    enemy: [
      ENEMIES.RingBoss,
      ENEMIES.Skeleton5,
      ENEMIES.Skeleton5,
      ENEMIES.Rambler
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health3)]
  },
  room83: {
    id: 83,
    type: "indoor",
    grid: SquareRM,
    wall: LavaWall,
    floor: Pavement,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: "wood2",
    eCon: 74,
    wCon: 84,
    furniture: [
      FURNITURE.Soc_TR,
      FURNITURE.Prince2_TL,
      FURNITURE.tallClock_TC,
      FURNITURE.wallLamp_LL,
      FURNITURE.wallLamp_LR,
      FURNITURE.Knightlore_BT,
      FURNITURE.Pitfall3_right_R
    ],
    enemy: [
      ENEMIES.Skeleton5,
      ENEMIES.Rambler,
      ENEMIES.DragonHunter,
      ENEMIES.DragonHunter
    ],
    items: []
  },
  room84: {
    id: 84,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall3,
    floor: BrickWall,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 83,
    furniture: [
      FURNITURE.fireplaceC,
      FURNITURE.PIC_DM_TR,
      FURNITURE.Hobbit_TL,
      FURNITURE.lanternpole2EL,
      FURNITURE.lanternpole2ER,
      FURNITURE.crack2L,
      FURNITURE.Lode_left,
      FURNITURE.Hero_BT,
      FURNITURE.Dig_right_R
    ],
    enemy: [
      ENEMIES.DragonHunter,
      ENEMIES.DragonHunter,
      ENEMIES.DragonShooter,
      ENEMIES.DragonBoss,
      ENEMIES.DragonHunter
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health3)]
  },
  room85: {
    id: 85,
    type: "indoor",
    grid: HRectRM,
    wall: DungeonWall,
    floor: BlackBrickWall2,
    ndoor: "open",
    edoor: null,
    sdoor: "green1",
    wdoor: "open",
    nCon: 81,
    sCon: 86,
    wCon: 100,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.EOB4_left_H_down,
      FURNITURE.Kara_right_H_up,
      FURNITURE.DM8_left_H_up,
      FURNITURE.Wardrobe2left_H,
      FURNITURE.wallLamp_LL_H,
      FURNITURE.wallLamp_LR_H_special
    ],
    enemy: [ENEMIES.DragonShooter, ENEMIES.Skelleton8],
    items: [$.extend(true, {}, ITEMS.health)]
  },
  room86: {
    id: 86,
    type: "indoor",
    grid: HRectRM,
    wall: StoneFloor,
    floor: WhiteCeramicWall2,
    ndoor: "open",
    edoor: "wood2",
    sdoor: null,
    wdoor: null,
    nCon: 85,
    eCon: 87,
    furniture: [
      FURNITURE.JSW2_BT,
      FURNITURE.PAC2_left_L_H,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.DragonShooter, ENEMIES.ZombieGirl3],
    items: [$.extend(true, {}, ITEMS.health2)]
  },
  room87: {
    id: 87,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall3,
    floor: BrickWall,
    ndoor: null,
    edoor: "wood2",
    sdoor: null,
    wdoor: "open",
    wCon: 86,
    eCon: 88,
    furniture: [
      FURNITURE.TR5_TL,
      FURNITURE.TR4_TR,
      FURNITURE.Pitfall_left_L,
      FURNITURE.Phara_right_R,
      FURNITURE.FF4_BT
    ],
    enemy: [
      ENEMIES.DragonHunter,
      ENEMIES.Shooter,
      ENEMIES.DragonShooter,
      ENEMIES.Hunter,
      ENEMIES.Death11
    ],
    items: [],
    container: {
      furniture: FURNITURE.Gold3,
      item: ITEMS.GoldBar3
    }
  },
  room88: {
    id: 88,
    type: "indoor",
    grid: HRectRM,
    wall: WhiteCeramicWall,
    floor: StoneFloor,
    ndoor: "wood1",
    edoor: null,
    sdoor: null,
    wdoor: "open",
    nCon: 89,
    wCon: 87,
    furniture: [
      FURNITURE.RRR_right_H,
      FURNITURE.wallLamp_LL_H,
      FURNITURE.wallLamp_LR_H,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.Robin_BT
    ],
    enemy: [ENEMIES.Death1],
    items: []
  },
  room89: {
    id: 89,
    name: "staircase",
    type: "stair",
    grid: StairRM,
    wall: BrickWall7,
    floor: StoneFloor2,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    nCon: 90,
    sCon: 88,
    furniture: [
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL
    ]
  },
  room90: {
    id: 90,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall,
    floor: Pavement2,
    ndoor: null,
    edoor: "wood2",
    sdoor: "open",
    wdoor: null,
    sCon: 89,
    eCon: 91,
    furniture: [
      FURNITURE.Ultima1_TR,
      FURNITURE.Ultima2_TL,
      FURNITURE.Falcon_left,
      FURNITURE.Arena_right_R,
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL
    ],
    enemy: [
      ENEMIES.Skeleton5,
      ENEMIES.Death2,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter2
    ],
    items: [$.extend(true, {}, ITEMS.bomb), $.extend(true, {}, ITEMS.ammo)]
  },
  room91: {
    id: 91,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: Pavement,
    ndoor: null,
    edoor: null,
    sdoor: "wood1",
    wdoor: "open",
    wCon: 90,
    sCon: 92,
    furniture: [
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.Maniac_TR,
      FURNITURE.AA7_TL,
      FURNITURE.Prince2_right,
      FURNITURE.LSL6_left_L,
      FURNITURE.GRB_TC
    ],
    enemy: [
      ENEMIES.Skeleton,
      ENEMIES.Devil,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter2,
      ENEMIES.Death1
    ],
    items: [$.extend(true, {}, ITEMS.time), $.extend(true, {}, ITEMS.ammo)]
  },
  room92: {
    id: 92,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall3,
    floor: StoneFloor,
    ndoor: "open",
    edoor: null,
    sdoor: "wood1",
    wdoor: null,
    nCon: 91,
    sCon: 93,
    furniture: [
      FURNITURE.wallLamp_BR,
      FURNITURE.wallLamp_BL,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT,
      FURNITURE.EOB4_right,
      FURNITURE.AA8_left,
      FURNITURE.HOB5_TR,
      FURNITURE.Eric_TL
    ],
    enemy: [
      ENEMIES.Skeleton,
      ENEMIES.Skeleton5,
      ENEMIES.Shooter,
      ENEMIES.Skelleton8
    ],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health2)]
  },
  room93: {
    id: 93,
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor4,
    floor: StoneFloor5,
    ndoor: "open",
    edoor: "wood2",
    sdoor: "green1",
    wdoor: null,
    nCon: 92,
    eCon: 94,
    sCon: 95,
    furniture: [
      FURNITURE.torch_TL,
      FURNITURE.torch_TR,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.torch_RL,
      FURNITURE.torch_RR,
      FURNITURE.HOB2_left_L,
      FURNITURE.HOB4_TR,
      FURNITURE.ST_TL,
      FURNITURE.SOC_BR
    ],
    enemy: [
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter2,
      ENEMIES.SkeletonHunter,
      ENEMIES.SkeletonHunter2
    ],
    items: [
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.health2),
      $.extend(true, {}, ITEMS.health)
    ]
  },
  room94: {
    id: 94,
    type: "indoor",
    grid: SquareRM,
    wall: TlakFloor2b,
    floor: TlakFloor,
    ndoor: null,
    edoor: "silver2",
    sdoor: null,
    wdoor: "open",
    wCon: 93,
    eCon: 24,
    furniture: [
      FURNITURE.Robin_TL,
      FURNITURE.Arena_TR,
      FURNITURE.Vixen2_BT,
      FURNITURE.WallLamp_RL,
      FURNITURE.WallLamp_RR,
      FURNITURE.WallLamp_LL,
      FURNITURE.WallLamp_LR,
      FURNITURE.Pitfall3_right_R,
      FURNITURE.Apshai_left_L
    ],
    enemy: [
      ENEMIES.Zombiehunter,
      ENEMIES.Zombiehunter,
      ENEMIES.Zombiehunter,
      ENEMIES.Zombiehunter,
      ENEMIES.Zombiehunter
    ],
    items: [],
    container: {
      furniture: FURNITURE.Sarcophagus,
      item: $.extend(true, {}, ITEMS.pouch)
    }
  },
  room95: {
    id: 95,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonFloor2,
    floor: StoneFloor3,
    ndoor: "open",
    edoor: null,
    sdoor: null,
    wdoor: null,
    nCon: 93,
    furniture: [
      FURNITURE.openGate,
      FURNITURE.tree1_TRbD,
      FURNITURE.C64_TL,
      FURNITURE.AA8_TR,
      FURNITURE.LSL7_right,
      FURNITURE.IM_left,
      FURNITURE.TR5_BT
    ],
    enemy: [
      ENEMIES.Snake,
      ENEMIES.Snake,
      ENEMIES.Snake,
      ENEMIES.SnakeHunter,
      ENEMIES.SnakeHunter,
      ENEMIES.GoldBoss
    ],
    items: [$.extend(true, {}, ITEMS.health3), $.extend(true, {}, ITEMS.life)]
  },
  room96: {
    id: 96,
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor3,
    floor: DungeonFloor2,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 79,
    nCon: 97,
    furniture: [
      FURNITURE.crack1_TR,
      FURNITURE.AMC_TL,
      FURNITURE.clock_TR,
      FURNITURE.wallLamp_BL,
      FURNITURE.wallLamp_BR,
      FURNITURE.SVS6_right,
      FURNITURE.Galaxian_left,
      FURNITURE.Frogger_BR
    ],
    enemy: [
      ENEMIES.SnakeHunter,
      ENEMIES.SnakeHunter,
      ENEMIES.DragonHunter2,
      ENEMIES.DragonHunter2
    ],
    items: [
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.bomb)
    ]
  },
  room97: {
    id: 97,
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor,
    floor: DungeonFloor,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 96,
    nCon: 98,
    furniture: [
      FURNITURE.Sorcery_left,
      FURNITURE.Cavelon_BR,
      FURNITURE.Horace_right,
      FURNITURE.AA9_TR,
      FURNITURE.DM7_TL,
      FURNITURE.wallLamp_LT,
      FURNITURE.wallLamp_RT
    ],
    enemy: [ENEMIES.Ugly, ENEMIES.Ugly, ENEMIES.Ugly, ENEMIES.Ugly],
    items: [$.extend(true, {}, ITEMS.ammo), $.extend(true, {}, ITEMS.health)]
  },
  room98: {
    id: 98,
    type: "indoor",
    grid: SquareRM,
    wall: StoneFloor2,
    floor: BrokenRuin,
    ndoor: "wood1",
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 97,
    nCon: 99,
    furniture: [
      FURNITURE.PC_WOW_TL,
      FURNITURE.AA2_right,
      FURNITURE.torch_BL,
      FURNITURE.torch_BR,
      FURNITURE.JSW_left,
      FURNITURE.Hero2_BR,
      FURNITURE.AA7_BL,
      FURNITURE.torch_TL,
      FURNITURE.torch_TR,
      FURNITURE.TUT_TR
    ],
    enemy: [
      ENEMIES.Skeleton7,
      ENEMIES.Skeleton5,
      ENEMIES.Skeleton,
      ENEMIES.ZombieQuick,
      ENEMIES.Ugly,
      ENEMIES.SkeletonHunter3
    ],
    items: [
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.health2),
      $.extend(true, {}, ITEMS.health2)
    ]
  },
  room99: {
    id: 99,
    type: "indoor",
    grid: SquareRM,
    wall: DungeonWall2,
    floor: SlateWall,
    ndoor: null,
    edoor: null,
    sdoor: "open",
    wdoor: null,
    sCon: 98,
    furniture: [
      FURNITURE.openGateS,
      FURNITURE.AMC_BT_L,
      FURNITURE.WALLS_BT_R,
      FURNITURE.GRB_TC,
      FURNITURE.CH1_TR,
      FURNITURE.TR8_TL,
      FURNITURE.SVS7_right,
      FURNITURE.DM8_left
    ],
    enemy: [
      ENEMIES.Behemoth,
      ENEMIES.Devil,
      ENEMIES.SnakeHunter,
      ENEMIES.DragonHunter,
      ENEMIES.ZombieGirl2,
      ENEMIES.Death22,
      ENEMIES.Death11,
      ENEMIES.Ugly,
      ENEMIES.Death1,
      ENEMIES.Death2
    ],
    items: [
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.life),
      $.extend(true, {}, ITEMS.ammo),
      $.extend(true, {}, ITEMS.ammo)
    ]
  },
  room100: {
    id: 100,
    type: "indoor",
    grid: SquareRM,
    wall: StoneWall,
    floor: ThachFloor,
    ndoor: null,
    edoor: "open",
    sdoor: null,
    wdoor: null,
    eCon: 85,
    sCon: 46,
    furniture: [
      FURNITURE.fireplaceR,
      FURNITURE.WallLamp_RL,
      FURNITURE.WallLamp_RR,
      FURNITURE.tallClock_TL,
      FURNITURE.Scramble_BT,
      FURNITURE.AA8_left,
      FURNITURE.TR2_TC
    ],
    items: [
      $.extend(true, {}, ITEMS.health3),
      $.extend(true, {}, ITEMS.life),
      $.extend(true, {}, ITEMS.ammo)
    ],
    enemy: [ENEMIES.DevilGreen, ENEMIES.SkeletonHunter, ENEMIES.Zombiehunter, ENEMIES.Death111]
  }
};
